module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    container: {
      center: true,
      padding: '1rem',
    },
    colors: {
      transparent: 'transparent',
      black: '#000',
      white: '#fff',
      'facebook' : '#3b5998',
      'twitter' : '#1da1f2',
      'pinterest' : '#bd081c',
      'instagram' : '#c32aa3',
      'indigo-dark': '#140d19',
      indigo: {
        100: '#e4e2e6',
        200: '#cac6cd',
        300: '#b1abb4',
        400: '#98909c',
        500: '#807585',
        600: '#695d6e',
        700: '#524559',
        800: '#362241',
        900: '#281930'
      },
      'gray-highlight': '#faf9fb',
      gray: {
        100: '#F4F4F6',
        200: '#E4E4E8',
        300: '#D3D4D9',
        400: '#B2B3BD',
        500: '#9193A1',
        600: '#838491',
        700: '#575861',
        800: '#414248',
        900: '#2C2C30',
      },
      blue: {
        100: '#E6F0F9',
        200: '#C0DAF0',
        300: '#99C4E6',
        400: '#2a9ffe',
        500: '#016BC1',
        600: '#0160AE',
        700: '#014074',
        800: '#003057',
        900: '#00203A',
      },
      pink: {
        100: '#FDE6F3',
        200: '#F9BFE1',
        300: '#F699CF',
        400: '#EF4DAB',
        500: '#E80087',
        600: '#D1007A',
        700: '#8B0051',
        800: '#68003D',
        900: '#460029',
      },
      green: {
        100: '#EDF8EC',
        200: '#D2EED0',
        300: '#B7E3B4',
        400: '#82CE7C',
        500: '#4CB944',
        600: '#44A73D',
        700: '#2E6F29',
        800: '#22531F',
        900: '#173814',
      },
      yellow: {
        100: '#FFFAE6',
        200: '#FFF3C0',
        300: '#FFEC9A',
        400: '#FFDE4E',
        500: '#FFD002',
        600: '#E6BB02',
        700: '#997D01',
        800: '#735E01',
        900: '#4D3E01',
      },
      red: {
        100: '#FFEBEC',
        200: '#FFCDCE',
        300: '#FFAEB1',
        400: '#FF7277',
        500: '#FF353C',
        600: '#E63036',
        700: '#992024',
        800: '#73181B',
        900: '#4D1012',
      },
      orange: {
        100: '#FFF5E8',
        200: '#FFE7C6',
        300: '#FFD9A4',
        400: '#FFBC60',
        500: '#FF9F1C',
        600: '#E68F19',
        700: '#995F11',
        800: '#73480D',
        900: '#4D3008',
      },
      teal: {
        100: '#F1FBF7',
        200: '#DCF4EB',
        300: '#C7EDDF',
        400: '#9EE0C6',
        500: '#74D3AE',
        600: '#68BE9D',
        700: '#467F68',
        800: '#345F4E',
        900: '#233F34',
      },
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
      '72': '20rem',
    },
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      xxl: '1600px',
    },
    fontFamily: {
      sans: [
        'Cabin',
        'Source Sans Pro',
        'system-ui',
        'BlinkMacSystemFont',
        '-apple-system',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ],
      round: [
        'Nunito',
        'Cabin',
        'Source Sans Pro',
        'system-ui',
        'BlinkMacSystemFont',
        '-apple-system',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ],
      serif: [
        'Times',
        'Times New Roman',
        'Lucida Bright',
        'Lucidabright',
        'Lucida Serif',
        'Lucida',
        'DejaVu Serif',
        'Bitstream Vera Serif',
        'Liberation Serif',
        'Georgia',
        'serif',
      ],
      mono: [
        'Constantia',
        'Lucida Bright',
        'Lucidabright',
        'Lucida Serif',
        'Lucida',
        'DejaVu Serif',
        'Bitstream Vera Serif',
        'Liberation Serif',
        'Georgia',
        'serif',
      ],
    },
    fontSize: {
      'xxs': '.625rem',     // 10px
      xs: '.75rem',     // 12px
      sm: '.875rem',    // 14px
      base: '1rem',     // 16px
      lg: '1.125rem',   // 18px
      xl: '1.25rem',    // 20px
      '2xl': '1.5rem',    // 24px
      '3xl': '1.875rem',  // 30px
      '4xl': '2.25rem',   // 36px
      '5xl': '3rem',      // 48px
      '6xl': '4rem',      // 64px
      '7xl': '5rem',      // 80px
      '8xl': '6rem',      // 96px
    },
    fontWeight: {
      hairline: 100,
      thin: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: 1,
      tight: 1.25,
      snug: 1.375,
      normal: 1.5,
      relaxed: 1.625,
      loose: 2,
    },
    letterSpacing: {
      tighter: '-.05em',
      tight: '-.025em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
    },
    textColor: theme => theme('colors'),
    backgroundColor: theme => theme('colors'),
    backgroundPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
      '3': '3px',
      '4': '4px',
      '5': '5px',
      '6': '6px',
      '7': '7px',
      '8': '8px',
    },
    borderColor: theme => ({
      ...theme('colors'),
      default: theme('colors.gray.300', 'currentColor'),
    }),
    borderRadius: {
      none: '0',
      sm: '0.125rem',
      default: '0.25rem',
      lg: '0.5rem',
      full: '9999px',
      '50': '50%',
    },
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      wait: 'wait',
      move: 'move',
      'not-allowed': 'not-allowed',
    },
    width: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.33333%',
      '2/3': '66.66667%',
      '1/4': '25%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '5/12': '41.66667%',
      '1/6': '16.66667%',
      '5/6': '83.33333%',
      '1/7': '14.2857142857143%',
      full: '100%',
      screen: '100vw',
    }),
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
    }),
    minWidth: {
      '0': '0',
      full: '100%',
    },
    minHeight: {
      '0': '0',
      full: '100%',
      screen: '100vh',
    },
    maxWidth: {
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      full: '100%',
      'big': '125%',
      'bigger': '137%',
      'double': '200%',
    },
    maxHeight: {
      '100': '100px',
      full: '100%',
      screen: '100vh',
    },
    padding: theme => theme('spacing'),
    margin: theme => ({ auto: 'auto', ...theme('spacing') }),
    negativeMargin: theme => theme('spacing'),
    objectPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    boxShadow: {
      default: '0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06)',
      md: '0 4px 6px -1px rgba(0, 0, 0, .1), 0 2px 4px -1px rgba(0, 0, 0, .06)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, .1), 0 4px 6px -2px rgba(0, 0, 0, .05)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, .1), 0 10px 10px -5px rgba(0, 0, 0, .04)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, .25)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
      outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
      none: 'none',
    },
    zIndex: {
      auto: 'auto',
      '0': 0,
      '10': 10,
      '20': 20,
      '30': 30,
      '40': 40,
      '50': 50,
    },
    opacity: {
      '0': '0',
      '5': '.05',
      '10': '.10',
      '20': '.20',
      '25': '.25',
      '30': '.30',
      '40': '.40',
      '50': '.5',
      '60': '.60',
      '70': '.70',
      '75': '.75',
      '80': '.80',
      '90': '.90',
      '100': '1',
    },
    fill: {
      current: 'currentColor',
    },
    stroke: {
      current: 'currentColor',
    },
    flex: {
      '1': '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none',
    },
    flexGrow: {
      '0': 0,
      default: 1,
    },
    flexShrink: {
      '0': 0,
      default: 1,
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    inset: {
      '0': 0,
      auto: 'auto',
    },
    // extra plugins
    textShadow: { // defaults to {}
      'default': '0 2px 5px rgba(0, 0, 0, 0.5), 0 1px 2px rgba(0, 0, 0, 0.25)',
      'lg': '0 2px 10px rgba(0, 0, 0, 0.5)',
    },
    gradients: {
      directions: { // defaults to these values
        't': 'to top',
        'tr': 'to top right',
        'r': 'to right',
        'br': 'to bottom right',
        'b': 'to bottom',
        'bl': 'to bottom left',
        'l': 'to left',
        'tl': 'to top left',
        '45': '45deg',
        '60': '-60deg',
        '135': '135deg',
        '150': '150deg',
      },
      colors: { // defaults to {}
        'blue': ['#016BC1', '#2a9ffe'],
        'pink': ['#E80087', '#EF4DAB'],
      },
    },
    scale: { // defaults to {}
      '90': '0.9',
      '95': '0.95',
      '100': '1',
      '105': '1.05',
      '110': '1.1',
    },
  },
  variants: {
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: [],
    borderColor: ['responsive', 'hover', 'focus', 'group-hover'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive'],
    flexDirection: ['responsive'],
    flexWrap: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    justifyContent: ['responsive'],
    alignContent: ['responsive'],
    flex: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    negativeMargin: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'hover'],
    outline: ['focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    inset: ['responsive'],
    resize: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus', 'group-hover'],
    fill: [],
    stroke: [],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus', 'group-hover'],
    fontSize: ['responsive'],
    fontStyle: ['responsive'],
    textTransform: ['responsive'],
    textDecoration: ['responsive', 'hover', 'focus'],
    fontSmoothing: ['responsive'],
    letterSpacing: ['responsive'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    wordBreak: ['responsive'],
    width: ['responsive'],
    zIndex: ['responsive'],
    // extra plugins
    textShadow: ['responsive', 'hover', 'group-hover'],
    gradients: ['responsive'], // defaults to ['responsive']
    scale: ['responsive', 'hover', 'group-hover'],
  },
  corePlugins: {},
  plugins: [
    require('tailwindcss-transitions')(),
    require('tailwindcss-typography')(),
    require('tailwindcss-gradients')(),
    require('tailwindcss-transforms')(),
  ],
}